spring:
  application:
     name:config-default
    
    # Eureka client configuration
    discovery:
      client:
        prefer-ip-address: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka
